#FROM mcr.microsoft.com/dotnet/core/aspnet AS build-env
#WORKDIR /app
#
## copy csproj and restore as distinct layers
#COPY *.csproj ./
#RUN dotnet restore
#
## copy everything else and build
#COPY . ./
#
#RUN dotnet publish -c Release -o out
#
## build runtime image
#FROM mcr.microsoft.com/dotnet/core/aspnet
#WORKDIR /app
#COPY --from=build-env /app/out .
#EXPOSE 80/tcp
#
#
#ENTRYPOINT ["dotnet", "WebApplication.dll"]

FROM mcr.microsoft.com/dotnet/core/sdk:2.1 AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:2.1
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "WebApplication.dll"]